// pantoneColors.js - Pre-categorized Pantone colors from the CSV data
// Contains most popular Pantone colors organized by category

// Categories and their display names
export const colorCategories = {
  'All': 'All Colors',
  'White/Light Gray': 'Whites',
  'Black/Gray': 'Blacks/Grays', 
  'Red/Pink': 'Reds/Pinks',
  'Orange/Yellow': 'Oranges/Yellows',
  'Yellow/Green': 'Yellow-Greens',
  'Green': 'Greens',
  'Blue': 'Blues',
  'Purple': 'Purples',
  'Neutrals': 'Neutrals',
  'Earthtones': 'Earth Tones'
};

// Quick preset colors for the main UI
export const quickPresets = {
  '#ffffff': 'Pantone 11-0601 TCX (Bright White)', 
  '#000000': 'Pantone 19-4005 TCX (Black)', 
  '#ff0000': 'Pantone 18-1664 TCX (True Red)', 
  '#0000ff': 'Pantone 19-3952 TCX (Spectrum Blue)', 
  '#ffff00': 'Pantone 13-0759 TCX (Lemon Chrome)', 
  '#00ff00': 'Pantone 15-6437 TCX (Kelly Green)', 
  '#888888': 'Pantone 17-1501 TCX (Frost Gray)', 
  '#d3d3d3': 'Pantone 13-4104 TCX (Silver Gray)', 
};

// Categorized Pantone colors - selected top colors per category
export const categorizedColors = {
  // Whites & Light Grays - 30 colors
  'White/Light Gray': [
    { name: "Egret", hex: "#f3ece0" },
    { name: "Snow White", hex: "#f2f0eb" },
    { name: "Bright White", hex: "#f4f5f0" },
    { name: "Cloud Dancer", hex: "#f0eee9" },
    { name: "Gardenia", hex: "#f1e8df" },
    { name: "Marshmallow", hex: "#f0eee4" },
    { name: "Blanc de Blanc", hex: "#e7e9e7" },
    { name: "Pristine", hex: "#f2e8da" },
    { name: "Whisper White", hex: "#ede6db" },
    { name: "White Asparagus", hex: "#e1dbc8" },
    { name: "Birch", hex: "#ddd5c7" },
    { name: "Bone White", hex: "#d7d0c0" },
    { name: "Milk", hex: "#d9d0c3" },
    { name: "Winter White", hex: "#f0efe4" },
    { name: "Cloud Cream", hex: "#e5dac9" },
    { name: "Pearled Ivory", hex: "#e4d9c1" },
    { name: "Silver Birch", hex: "#d1ccbd" },
    { name: "Crystal Gray", hex: "#d7cbc4" },
    { name: "Ashes of Roses", hex: "#c5b5ac" },
    { name: "Silver Gray", hex: "#c1bab2" },
    { name: "Moonstruck", hex: "#d2cdc9" },
    { name: "Dove", hex: "#c0b6b2" },
    { name: "Wind Chime", hex: "#c4bcb7" },
    { name: "Rainy Day", hex: "#d1c7bf" },
    { name: "String", hex: "#d6ceba" },
    { name: "Fog", hex: "#d0c5b1" },
    { name: "Oyster White", hex: "#d2caaf" },
    { name: "Moonbeam", hex: "#cdc9c0" },
    { name: "Smoke", hex: "#b3ada5" },
    { name: "Moon Rock", hex: "#958f8a" }
  ],
  
  // Blacks & Grays - 25 colors
  'Black/Gray': [
    { name: "Jet Black", hex: "#2d2c2f" },
    { name: "Black", hex: "#2b2b2b" },
    { name: "Phantom", hex: "#39373b" },
    { name: "Stretch Limo", hex: "#2b2c30" },
    { name: "Moonless Night", hex: "#2f2d30" },
    { name: "Anthracite", hex: "#28282d" },
    { name: "Caviar", hex: "#292a2d" },
    { name: "Pirate Black", hex: "#363838" },
    { name: "Raven", hex: "#413e3d" },
    { name: "Black Olive", hex: "#48413b" },
    { name: "Dark Gull Gray", hex: "#625d5d" },
    { name: "Steel Gray", hex: "#726f70" },
    { name: "Castlerock", hex: "#5f5e62" },
    { name: "Nine Iron", hex: "#46434a" },
    { name: "Forged Iron", hex: "#48464b" },
    { name: "Asphalt", hex: "#434447" },
    { name: "Iron Gate", hex: "#4e5055" },
    { name: "Gunmetal", hex: "#5c5d5b" },
    { name: "Charcoal Gray", hex: "#6c6c6a" },
    { name: "Dark Shadow", hex: "#4a4b4d" },
    { name: "Peat", hex: "#3b3a36" },
    { name: "Meteorite", hex: "#2c2c32" },
    { name: "Ebony", hex: "#2b2c26" },
    { name: "Jet Set", hex: "#262c2a" },
    { name: "Blackened Pearl", hex: "#4e4b46" }
  ],
  
  // Reds & Pinks - 30 colors
  'Red/Pink': [
    { name: "Tomato", hex: "#ce2029" },
    { name: "Fiery Red", hex: "#d01c1f" },
    { name: "High Risk Red", hex: "#c71f2d" },
    { name: "Lollipop", hex: "#cc1c3b" },
    { name: "Chinese Red", hex: "#be132d" },
    { name: "Scarlet", hex: "#bc2b3d" },
    { name: "Crimson", hex: "#ae0e36" },
    { name: "Ruby Wine", hex: "#77202f" },
    { name: "Rio Red", hex: "#8a1f1c" },
    { name: "Biking Red", hex: "#77212e" },
    { name: "Tibetan Red", hex: "#782a39" },
    { name: "Samba", hex: "#a2182e" },
    { name: "True Red", hex: "#bf1932" },
    { name: "Racing Red", hex: "#bd162c" },
    { name: "Barbados Cherry", hex: "#aa0a27" },
    { name: "Chili Pepper", hex: "#9b1b30" },
    { name: "Pink Carnation", hex: "#ff6d83" },
    { name: "Camellia Rose", hex: "#ef7699" },
    { name: "Shocking Pink", hex: "#dd3c7a" },
    { name: "Raspberry Sorbet", hex: "#d2386c" },
    { name: "Fuchsia Rose", hex: "#c74375" },
    { name: "Rouge Red", hex: "#ab4b77" },
    { name: "Rose Violet", hex: "#c0428a" },
    { name: "Wild Orchid", hex: "#d979a2" },
    { name: "Aurora Pink", hex: "#e880a1" },
    { name: "Pink Lady", hex: "#f8a3bc" },
    { name: "Sachet Pink", hex: "#f2afc1" },
    { name: "Prism Pink", hex: "#f0a1b8" },
    { name: "Peony Pink", hex: "#ed91a8" },
    { name: "Honeysuckle", hex: "#d94f70" }
  ],
  
  // Oranges & Yellows - 30 colors
  'Orange/Yellow': [
    { name: "Vibrant Orange", hex: "#ff7420" },
    { name: "Persimmon Orange", hex: "#f26531" },
    { name: "Exuberance", hex: "#e35205" },
    { name: "Orange Popsicle", hex: "#ff7913" },
    { name: "Tangerine", hex: "#fa6b35" },
    { name: "Harvest Pumpkin", hex: "#d95b2b" },
    { name: "Mandarin Orange", hex: "#ec6a37" },
    { name: "Flame Orange", hex: "#f5632d" },
    { name: "Autumn Maple", hex: "#c46215" },
    { name: "Hawaiian Sunset", hex: "#ba5140" },
    { name: "Burnt Sienna", hex: "#c65d52" },
    { name: "Ginger", hex: "#c15e3c" },
    { name: "Russet Orange", hex: "#e47956" },
    { name: "Coral", hex: "#ed7464" },
    { name: "Cantaloupe", hex: "#ffa177" },
    { name: "Melon", hex: "#fe9762" },
    { name: "Golden Ochre", hex: "#c77a3e" },
    { name: "Gold Flame", hex: "#b67c51" },
    { name: "Cadmium Yellow", hex: "#f9c000" },
    { name: "Spectra Yellow", hex: "#f7b718" },
    { name: "Vibrant Yellow", hex: "#f5d000" },
    { name: "Lemon Chrome", hex: "#ffc300" },
    { name: "Buttercup", hex: "#fac12f" },
    { name: "Saffron", hex: "#ffc636" },
    { name: "Freesia", hex: "#f9db35" },
    { name: "Lemon", hex: "#f3bf08" },
    { name: "Maize", hex: "#eec64f" },
    { name: "Aspen Gold", hex: "#ffd662" },
    { name: "Mellow Yellow", hex: "#f0dd9e" },
    { name: "Canary Yellow", hex: "#dfd87f" }
  ],
  
  // Yellow-Greens - 20 colors
  'Yellow/Green': [
    { name: "Lime Punch", hex: "#c0d725" },
    { name: "Lime Green", hex: "#9fc131" },
    { name: "Jasmine Green", hex: "#7ec845" },
    { name: "Green Flash", hex: "#79c753" },
    { name: "Classic Green", hex: "#39a845" },
    { name: "Island Green", hex: "#2baa60" },
    { name: "Kelly Green", hex: "#339c5e" },
    { name: "Leprechaun", hex: "#318e5a" },
    { name: "Treetop", hex: "#476a30" },
    { name: "Piquant Green", hex: "#769358" },
    { name: "Forest Green", hex: "#6b8d53" },
    { name: "Fluorite Green", hex: "#699158" },
    { name: "Patina Green", hex: "#b9eab3" },
    { name: "Greenery", hex: "#88b04b" },
    { name: "Paradise Green", hex: "#b2e79f" },
    { name: "Spring Bouquet", hex: "#6dce87" },
    { name: "Online Lime", hex: "#44883c" },
    { name: "Macaw Green", hex: "#9bb53e" },
    { name: "Sap Green", hex: "#afcb80" },
    { name: "Fern", hex: "#9aa067" }
  ],
  
  // Greens - 25 colors
  'Green': [
    { name: "Arcadian Green", hex: "#1e3d14" },
    { name: "Eden", hex: "#264e36" },
    { name: "Hunter Green", hex: "#3f5f48" },
    { name: "Myrtle", hex: "#255c3f" },
    { name: "Posy Green", hex: "#325b51" },
    { name: "Trekking Green", hex: "#355048" },
    { name: "Shady Glade", hex: "#405e5a" },
    { name: "Jungle", hex: "#3b5c3f" },
    { name: "Mountain View", hex: "#2e3f34" },
    { name: "Pineneedle", hex: "#334d41" },
    { name: "Pine Forest", hex: "#2a3b30" },
    { name: "Evergreen", hex: "#11574a" },
    { name: "Greener Pastures", hex: "#306d54" },
    { name: "Teal", hex: "#478589" },
    { name: "Arcadia", hex: "#00a28a" },
    { name: "Mint Leaf", hex: "#00b28f" },
    { name: "Biscay Green", hex: "#55c6bd" },
    { name: "Lucite Green", hex: "#7ad2cb" },
    { name: "Blue Light", hex: "#acdfdd" },
    { name: "Aqua Glass", hex: "#d1f0f1" },
    { name: "Bottle Green", hex: "#427d6d" },
    { name: "Beveled Glass", hex: "#7accb8" },
    { name: "Deep Mint", hex: "#009e6d" },
    { name: "Jolly Green", hex: "#007844" },
    { name: "Columbia", hex: "#8cc1d3" }
  ],
  
  // Blues - 25 colors
  'Blue': [
    { name: "Classic Blue", hex: "#0f4c81" },
    { name: "Turkish Sea", hex: "#195190" },
    { name: "Strong Blue", hex: "#235ba8" },
    { name: "Snorkel Blue", hex: "#034f84" },
    { name: "True Blue", hex: "#1e5aa0" },
    { name: "Directoire Blue", hex: "#0061a3" },
    { name: "Star Sapphire", hex: "#386192" },
    { name: "Brilliant Blue", hex: "#0075c4" },
    { name: "Princess Blue", hex: "#00539c" },
    { name: "Diva Blue", hex: "#247ba0" },
    { name: "Blue Horizon", hex: "#4e91c5" },
    { name: "Crystal Blue", hex: "#a1cee2" },
    { name: "Clearwater", hex: "#aad5db" },
    { name: "Placid Blue", hex: "#8daccd" },
    { name: "Airy Blue", hex: "#92b6d5" },
    { name: "Cerulean", hex: "#9bb7d4" },
    { name: "Heritage Blue", hex: "#5d96bc" },
    { name: "Faience", hex: "#2e5978" },
    { name: "Blue Iris", hex: "#5a5b9f" },
    { name: "Bleached Denim", hex: "#646f9b" },
    { name: "Easter Egg", hex: "#919bc9" },
    { name: "Jacaranda", hex: "#848dc5" },
    { name: "Deep Periwinkle", hex: "#7c83bc" },
    { name: "Lavender Blue", hex: "#9d9be8" },
    { name: "Blue Turquoise", hex: "#53b0ae" }
  ],
  
  // Purples - 20 colors
  'Purple': [
    { name: "Grape Juice", hex: "#673c47" },
    { name: "Plum Purple", hex: "#51304e" },
    { name: "Mysterioso", hex: "#66545e" },
    { name: "Loganberry", hex: "#5d3c6b" },
    { name: "Purple Magic", hex: "#663271" },
    { name: "Imperial Palace", hex: "#604e7a" },
    { name: "Grape Jam", hex: "#725bad" },
    { name: "Amethyst", hex: "#865ca3" },
    { name: "Royal Lilac", hex: "#774d8e" },
    { name: "Hyacinth", hex: "#936ca7" },
    { name: "Baja Blue", hex: "#5f6db0" },
    { name: "Liberty", hex: "#4e62ab" },
    { name: "Violet Storm", hex: "#5c619d" },
    { name: "Amparo Blue", hex: "#4d5b9e" },
    { name: "Clematis Blue", hex: "#5a67a8" },
    { name: "Mauve Mist", hex: "#c49bd4" },
    { name: "African Violet", hex: "#b085b7" },
    { name: "Paisley Purple", hex: "#8b79b1" },
    { name: "Amethyst Orchid", hex: "#926aa6" },
    { name: "Purple Opulence", hex: "#60569a" }
  ],
  
  // Neutrals - 25 colors
  'Neutrals': [
    { name: "Vanilla Ice", hex: "#f4f2d6" },
    { name: "Almond Buff", hex: "#e2d3ad" },
    { name: "Sweet Corn", hex: "#f9ebc8" },
    { name: "Cream Gold", hex: "#dec5a5" },
    { name: "Transparent Yellow", hex: "#e4ce8f" },
    { name: "Double Cream", hex: "#f4e3b5" },
    { name: "Parchment", hex: "#dfd1be" },
    { name: "Light Taupe", hex: "#ad9b8d" },
    { name: "Taupe Gray", hex: "#8e7c71" },
    { name: "Twig", hex: "#a39a90" },
    { name: "Eucalyptus", hex: "#b1a992" },
    { name: "Stone Gray", hex: "#928475" },
    { name: "Pure Cashmere", hex: "#ada396" },
    { name: "Moon Mist", hex: "#80817d" },
    { name: "Opal Gray", hex: "#a49e9e" },
    { name: "Satellite", hex: "#9f8d89" },
    { name: "Cliff Gray", hex: "#a49592" },
    { name: "Silver Filigree", hex: "#aeabac" },
    { name: "Rose Dust", hex: "#a99592" },
    { name: "Taupe", hex: "#9f8e82" },
    { name: "Simply Taupe", hex: "#ad9279" },
    { name: "Plaza Taupe", hex: "#887e6d" },
    { name: "Timber Wolf", hex: "#8d8070" },
    { name: "Cub", hex: "#6e5c50" },
    { name: "Fossil", hex: "#806f63" }
  ],
  
  // Earth Tones - 30 colors
  'Earthtones': [
    { name: "Sandstorm", hex: "#c5b358" },
    { name: "Bamboo", hex: "#d2b15a" },
    { name: "Antelope", hex: "#b19664" },
    { name: "Dijon", hex: "#97754c" },
    { name: "Bronze Mist", hex: "#a78c59" },
    { name: "Dull Gold", hex: "#8a6c32" },
    { name: "Butterum", hex: "#c68f65" },
    { name: "Adobe", hex: "#a3623b" },
    { name: "Biscotti", hex: "#dac7ab" },
    { name: "Lark", hex: "#c3a992" },
    { name: "Tan", hex: "#b69574" },
    { name: "Toasted Almond", hex: "#d2b49c" },
    { name: "Desert Dust", hex: "#e0c5a8" },
    { name: "Semolina", hex: "#cdb795" },
    { name: "Cornhusk", hex: "#f4efc1" },
    { name: "Boulder", hex: "#b1a28c" },
    { name: "Oatmeal", hex: "#cbc1ae" },
    { name: "Croissant", hex: "#c5aa74" },
    { name: "Dried Herb", hex: "#847a59" },
    { name: "Elmwood", hex: "#8a7357" },
    { name: "Kangaroo", hex: "#725e43" },
    { name: "Ermine", hex: "#836b4f" },
    { name: "Caramel Cafe", hex: "#864c24" },
    { name: "Glazed Ginger", hex: "#91552b" },
    { name: "Hazel", hex: "#ae7250" },
    { name: "Sierra", hex: "#985c41" },
    { name: "Thrush", hex: "#936b4f" },
    { name: "Toffee", hex: "#755139" },
    { name: "Brown Patina", hex: "#834e40" },
    { name: "Rawhide", hex: "#865e49" }
  ]
};

// Function to get all colors as a flattened array
export function getAllColors() {
  let allColors = [];
  Object.keys(categorizedColors).forEach(category => {
    allColors = [...allColors, ...categorizedColors[category]];
  });
  return allColors;
}
